#!/usr/bin/env python3
"""
Generate ATTRIBUTION.md — the license/credits NOTICE for LeafAlert's training data.

Every image fetched by scripts/fetch_*.py records its license, photographer and
source observation in the staging manifest. Committed images record their source
observation in TrainingData/manifest.jsonl. This joins the two and emits a
human-readable NOTICE crediting every photographer whose work trained the model.

CC BY and CC BY-NC both carry an ATTRIBUTION obligation, and CC BY-NC forbids
commercial use — so this file must ship with (or be linked from) any distribution
of the model, and the NonCommercial constraint must be honored.

Usage:
    python3 scripts/generate_attribution.py
    python3 scripts/generate_attribution.py --out ATTRIBUTION.md
"""

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
POOL_MANIFEST = PROJECT_ROOT / "TrainingData" / "manifest.jsonl"
STAGING_ROOT = PROJECT_ROOT / "data_staging"
CLASSES = ["poison_ivy", "poison_oak", "poison_sumac", "safe_plants"]

# Human-readable license names + whether they permit commercial use.
LICENSE_INFO = {
    "cc0": ("CC0 1.0 (public domain dedication)", True),
    "cc-by": ("CC BY 4.0", True),
    "cc-by-nc": ("CC BY-NC 4.0 (NonCommercial)", False),
    "CC0_1_0": ("CC0 1.0 (public domain dedication)", True),
    "CC_BY_4_0": ("CC BY 4.0", True),
}


def load_jsonl(path: Path):
    if not path.exists():
        return []
    out = []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if line:
                try:
                    out.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    return out


def count_pool_images() -> int:
    total = 0
    for cls in CLASSES:
        d = PROJECT_ROOT / "TrainingData" / cls
        if d.is_dir():
            total += sum(1 for p in d.iterdir()
                         if p.suffix.lower() in {".jpg", ".jpeg", ".png"})
    return total


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=str(PROJECT_ROOT / "ATTRIBUTION.md"))
    args = ap.parse_args()

    committed = load_jsonl(POOL_MANIFEST)
    # Index every staged provenance row by observation id (all sources).
    by_obs = {}
    for mf in sorted(STAGING_ROOT.glob("*/manifest.jsonl")):
        for r in load_jsonl(mf):
            oid = r.get("observation_id") or r.get("occurrence_id")
            if oid is not None:
                by_obs.setdefault(oid, r)

    # Join committed images -> provenance.
    joined, unprovenanced = [], 0
    for rec in committed:
        prov = by_obs.get(rec.get("observation_id"))
        if prov:
            joined.append((rec, prov))
        else:
            unprovenanced += 1

    pool_total = count_pool_images()
    # Images in the pool with no manifest row at all (pre-expansion originals).
    untracked = pool_total - len(committed)

    lic_counts = Counter(p.get("license", "unknown") for _, p in joined)
    class_counts = Counter(r.get("class", "?") for r, _ in joined)

    # Group credits: photographer -> license -> set of observation ids
    credits = defaultdict(lambda: defaultdict(set))
    for _, p in joined:
        name = (p.get("photographer_name") or p.get("photographer_login")
                or p.get("attribution") or "Unknown")
        credits[str(name).strip()][p.get("license", "unknown")].add(p.get("observation_id"))

    noncommercial = any(not LICENSE_INFO.get(l, ("", True))[1] for l in lic_counts)

    L = []
    L.append("# LeafAlert — Training Data Attribution & Licensing NOTICE\n")
    L.append("This file is generated by `scripts/generate_attribution.py`. "
             "Regenerate it after any dataset fetch.\n")

    if noncommercial:
        L.append("## ⚠️ NonCommercial constraint\n")
        L.append("**Part of this training set is licensed CC BY-NC (NonCommercial). "
                 "The resulting model must not be used commercially unless those images "
                 "are removed and the model retrained.** If you need a commercially "
                 "usable model, re-fetch with `--license cc0,cc-by` only and retrain.\n")

    L.append("## Summary\n")
    L.append(f"- Training pool: **{pool_total}** images across {', '.join(CLASSES)}.")
    L.append(f"- With recorded provenance: **{len(joined)}** images "
             f"from **{len({p.get('observation_id') for _, p in joined})}** source "
             f"observations by **{len(credits)}** photographers.")
    if untracked > 0:
        L.append(f"- ⚠️ **{untracked}** pre-expansion images have **no recorded license "
                 f"or attribution** (they predate the provenance-tracking fetchers). "
                 f"Their licensing is UNVERIFIED — audit or replace them before any "
                 f"public distribution.")
    L.append("")
    L.append("License breakdown of the provenance-tracked images:\n")
    L.append("| License | Images | Commercial use |")
    L.append("|---|---|---|")
    for lic, n in lic_counts.most_common():
        label, commercial = LICENSE_INFO.get(lic, (lic, None))
        ok = "yes" if commercial else ("no" if commercial is False else "unknown")
        L.append(f"| {label} | {n} | {ok} |")
    L.append("")
    L.append("Per-class (provenance-tracked): "
             + ", ".join(f"{c} {class_counts.get(c, 0)}" for c in CLASSES) + "\n")

    L.append("## Source\n")
    L.append("Images were retrieved from [iNaturalist](https://www.inaturalist.org) "
             "(research-grade observations) under the licenses above. Each credit below "
             "links to the source observation, which carries the authoritative license "
             "and photographer information.\n")

    L.append("## Credits\n")
    L.append("Thank you to the following photographers, whose openly-licensed "
             "observations made this model possible.\n")
    for name in sorted(credits, key=lambda s: s.lower()):
        for lic, obs in sorted(credits[name].items()):
            label = LICENSE_INFO.get(lic, (lic, None))[0]
            ids = sorted(o for o in obs if o is not None)
            shown = ", ".join(
                f"[{o}](https://www.inaturalist.org/observations/{o})" for o in ids[:8]
            )
            more = f" (+{len(ids) - 8} more)" if len(ids) > 8 else ""
            L.append(f"- **{name}** — {label} — {len(ids)} observation(s): {shown}{more}")
    L.append("")

    out = Path(args.out)
    out.write_text("\n".join(L))
    print(f"Wrote {out} — {len(joined)} attributed images, {len(credits)} photographers.")
    if untracked > 0:
        print(f"WARNING: {untracked} pool images have no recorded provenance/license.")
    if noncommercial:
        print("WARNING: training set includes CC BY-NC images — NonCommercial constraint applies.")


if __name__ == "__main__":
    main()
